---
version: "3.8"

services:

  caller:
    image: golang:1.17.1-bullseye
    ports:
      - ${CALLER_PORT}:${CALLER_PORT}
    environment:
      PORT: ${CALLER_PORT}
      CALLEE_HOST: callee
      CALLEE_PORT: ${CALLEE_PORT}
    volumes:
      - .:/go/src/github.com/110y/grpc-go-connection-demo:cached
    working_dir: /go/src/github.com/110y/grpc-go-connection-demo
    command: go run ./caller

  callee:
    image: golang:1.17.1-bullseye
    ports:
      - ${CALLEE_PORT}:${CALLEE_PORT}
    environment:
      PORT: ${CALLEE_PORT}
    volumes:
      - .:/go/src/github.com/110y/grpc-go-connection-demo:cached
    working_dir: /go/src/github.com/110y/grpc-go-connection-demo
    command: go run ./callee
